language: ruby
rvm:
- 2.3.3 #reasonably recent
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH #required settings for travis
addons:
  firefox: "44.0" # Had to downgrade to something compatible with slimer
cache: bundler # speed up the build
before_script:
  - . $HOME/.nvm/nvm.sh # Allows us to install a more recent node
  - nvm install stable # Install it
  - nvm use stable # Use it
  - npm install # Install project dependencies
  - npm install -g casperjs slimerjs@0.10.3 a11y # Install dependencies which prefer to be global
  - sh -e /etc/init.d/xvfb start # start xvfb for slimer
script: npm run test
notifications:
  slack:
    secure: kuJVE8NDUG/Hn9VyZM7o3e/MV8n1Qk48tUkcwYggTqUDSm8gBBQewti/PLS1qDE6mtBrXsAlqP1LBdGeJI8qQQSYyS79vwLkICKM32fiMDOJU8CFGD9oMNxmjOMK7gCnLf9WjYTgsJbpQdUlHUAE61nv4CtHWUoiPDjdiAzlXpn2+FvyFsLJiiv/QYHo+DVxTlNZrbovDn/UKNDQqYPPwkY40PrLTO18sykmNwflFCGmnMvsv/ownOoNyXveDzCsq2dx8BPQ/+FbCDGeob62ymc+bdcHJnjHFBv2ceHWYfYLXDijDonioTcITj0uYCIFV76zfjgylCYlhd5fLsJyAxwQsTOk29muJ2iQNgPI/5kSXdm6pOWY4ZGGOwfP3hYtJ+UsT6d1f+aepLc6ZRGOM5dQ/Sx1QbNKapX91jmT2wpFfZinM4Wvgoe61RtFTTSN2p5cBK5ZHCcsc/Z5s+vZSizYc9c7pQDBdPK8TbZgzGjgXb6a7CaQDKFhHh2M14Nv3VatDVrynUvp2Uz6aL8DiZ3I1oCnmeKleiWi1qxlFLJ4zoSSQWlzK0joND3n6mVI5QmMJ3hRdTQSwbph+is9zZr8lFyHFEhpF5M/88PlKG9pZ2tHvY+LTvGp9E8AKvuUjQc13OxT0DU13ja2/3kFXlzBme2dB+0Jg0thxPii5RA=
