title: Meedan
email: info@meedan.com
description: >- # this means to ignore newlines until "baseurl:"
  A team of designers, technologists and journalists who build software and design human-powered initiatives for newsrooms, NGOs and academic institutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: meedan
github_username:  meedan

# Build settings
markdown: kramdown

# Timezone
timezone: America/Vancouver

plugins:
  - jekyll-seo-tag

# Config elements specific to jeckyll-seo-tag
# https://github.com/jekyll/jekyll-seo-tag
twitter:
  username: meedan
  card:     "summary_large_image"
logo: /images/meedan-logo-horizontal-3@2x.png
seo:
  type: Organization
    
social:
  name: Meedan
  links:
    - https://twitter.com/meedan
    - https://facebook.com/meedan

# Server Config options
livereload: true    # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port

# Include _redirects file
include: [_redirects]

# Get data from Contentful Develop Environment
contentful:
  output: true
  spaces:
    - annualReports: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'annualReport'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - sections: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'section'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - module2ColumnContents: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'module2ColumnContent'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - stats: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'stat'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - cards: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'moduleCard'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - userGuides: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'userGuide'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - projects: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'project'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - topics: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'topic'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - stories: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          locale: '*'
          content_type: 'story'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        content_types:
          story: StoryMapper
        destination: 'contentful/spaces/'
    - jobs: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'job'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        content_types:
          job: JobsMapper
        destination: 'contentful/spaces/'
    - pages: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'page'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - moduleStories: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'moduleStories'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - moduleList: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'moduleList'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - moduleCards: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'moduleCards'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - pages: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'page'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - events: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'event'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        content_types:
          event: EventsMapper
        destination: 'contentful/spaces/'
    - moduleEvents: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'moduleEvents'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'


# Generate pages from Contentful data files
page_gen-dirs: true
page_gen:
  - data: 'contentful.spaces.annualReports.annualReport'
    template: 'annual_report'
    name: 'slug'
    dir: '/'
  - data: 'contentful.spaces.userGuides.userGuide'
    template: 'user_guide'
    name: 'slug'
    dir: '/user-guides/'
  - data: 'contentful.spaces.projects.project'
    template: 'project'
    name: 'slug'
    dir: '/projects/'
  - data: 'contentful.spaces.stories.story'
    template: 'story'
    name: 'slug'
    dir: '/blog/'
  - data: 'contentful.spaces.pages.page'
    template: 'page'
    name: 'slug'
    dir: '/'
  - data: 'contentful.spaces.stories.story'
    template: 'story-es'
    name: 'slug'
    dir: '/blog/es/'
    filter: 'body-es'
  - data: 'contentful.spaces.stories.story'
    template: 'story-pt'
    name: 'slug'
    dir: '/blog/pt/'
    filter: 'body-pt'
  - data: 'contentful.spaces.stories.story'
    template: 'story-ar'
    name: 'slug'
    dir: '/blog/ar/'
    filter: 'body-ar'
  - data: 'contentful.spaces.jobs.job'
    template: 'job'
    name: 'slug'
    dir: '/jobs/'
  - data: 'contentful.spaces.events.event'
    template: 'event'
    name: 'slug'
    dir: '/events/'

# Search
algolia:
  application_id: XVQE72Q0TQ
  index_name:     meedan.com
  nodes_to_index: 'p,blockquote'
  search_only_api_key: d031b4f0809f3999da155451bffba6db
  files_to_exclude:
    - projects/check-global/index.html
    - blog/caio-almeida-on-software-that-serves-a-global-community/index.html
    - blog/going-virtual-how-meedan-is-doing-the-conference-thing-online/index.html
    - /blog/meet-our-regional-program-managers-apac-latin-america-and-africa/index.html
    - /blog/database-of-expert-sourced-covid-19-information-for-fact-checkers/index.html
    - /blog/new-microgrants-for-covid-19-media-work-in-emerging-economies/index.html
    - /blog/tech-and-check-2020/index.html
    - /blog/voicesontherise-mediathon-in-mexico/index.html
    - /blog/3-things-we-learned-on-designing-collaborations-from-the-reboots-masterclass/index.html
    - /blog/meedan-recognizes-world-press-freedom-day/index.html
    - /blog/textfakes-deepfakes-and-the-power-of-context/index.html
    - /blog/elections-promises-and-covid-19-three-years-in-supporting-fact-checking-and/index.html
    - /blog/es/new-microgrants-for-covid-19-media-work-in-emerging-economies/index.html
    - /blog/pt/new-microgrants-for-covid-19-media-work-in-emerging-economies/index.html
    - /blog/ar/new-microgrants-for-covid-19-media-work-in-emerging-economies/index.html
    - /jobs/research-fellow/index.html