title: Meedan
email: info@meedan.com
description: >- # this means to ignore newlines until "baseurl:"
  A team of designers, technologists and journalists who focus on open source investigation of digital media and crowdsourced translation of social media.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: meedan
github_username:  meedan

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag

# Config elements specific to jeckyll-seo-tag
# https://github.com/jekyll/jekyll-seo-tag
twitter:
  username: meedan
logo: /images/meedan-logo-horizontal-3@2x.png

social:
  name: Meedan
  links:
    - https://twitter.com/meedan
    - https://facebook.com/meedan

# Server Config options
livereload: true    # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port

# Get data from Contentful Develop Environment
contentful:
  output: true
  spaces:
    - annualReports: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'annualReport'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - sections: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'section'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - module2ColumnContents: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'module2ColumnContent'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - stats: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'stat'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - moduleCards: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'moduleCard'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - userGuides: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'userGuide'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - projects: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'project'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - stories: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'story'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'
    - jobs: 
        space: ENV_CONTENTFUL_M_SPACE_ID
        access_token: ENV_CONTENTFUL_M_ACCESS_TOKEN
        cda_query:
          content_type: 'job'
        client_options:
          api_url: ENV_CONTENTFUL_API_URL
        all_entries: true
        destination: 'contentful/spaces/'


# Generate pages from Contentful data files
page_gen-dirs: true
page_gen:
  - data: 'contentful.spaces.annualReports.annualReport'
    template: 'annual_report'
    name: 'slug'
    dir: '/'
  - data: 'contentful.spaces.userGuides.userGuide'
    template: 'user_guide'
    name: 'slug'
    dir: '/user-guides/'
  - data: 'contentful.spaces.projects.project'
    template: 'project'
    name: 'slug'
    dir: '/projects/'
  - data: 'contentful.spaces.stories.story'
    template: 'story'
    name: 'slug'
    dir: '/journal/'
  - data: 'contentful.spaces.jobs.job'
    template: 'job'
    name: 'slug'
    dir: '/jobs/'